- type: antag
  id: CultYogg
  name: roles-antag-cult-yogg-name
  antagonist: true
  setPreference: true
  objective: roles-antag-cult-yogg-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 18000 # 5h
